#!/bin/sh

test -x $(which duplicity) || exit 0
. ~/.backup-to-s3-config

export PASSPHRASE
export AWS_SECRET_ACCESS_KEY
export AWS_ACCESS_KEY_ID 

$(which duplicity) --full-if-older-than 3M --encrypt-key $ENCRYPTION_KEY --sign-key $SIGNATURE_KEY --volsize=250 --include=/home/mike/Documents --include=/home/mike/Projects --include=/home/mike/Videos --include=/home/mike/Pictures --exclude=/** / $BUCKET_NAME
$(which duplicity) remove-all-but-n-full 3 --force $BUCKET_NAME

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export PASSPHRASE=
