#!/bin/sh

test -x $(which duplicity) || exit 0
. ~/.backup-to-s3-config

export PASSPHRASE
export AWS_SECRET_ACCESS_KEY
export AWS_ACCESS_KEY_ID 

$(which duplicity) --full-if-older-than $FULL_BACKUP --encrypt-key $ENCRYPTION_KEY --sign-key $SIGNATURE_KEY --volsize=250 $BACKUP_INCLUDES --exclude=/** / $BUCKET_NAME
$(which duplicity) remove-all-but-n-full $NUM_FULL_TO_KEEP --force $BUCKET_NAME

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export PASSPHRASE=
