#!/bin/sh

test -x $(which duplicity) || exit 0
. ~/.backup-to-s3-config

export PASSPHRASE
export AWS_SECRET_ACCESS_KEY
export AWS_ACCESS_KEY_ID 

$(which duplicity) collection-status --encrypt-key $ENCRYPTION_KEY --sign-key $SIGNATURE_KEY $BUCKET_NAME

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export PASSPHRASE=

