#!/bin/sh

# Performs incremental backups (or full if none exist). Modify as needed.

test -x $(which duplicity) || exit 0
. /root/.passphrase

export PASSPHRASE
export AWS_SECRET_ACCESS_KEY
export AWS_ACCESS_KEY_ID 

$(which duplicity) --encrypt-key [gpg encryption key] --sign-key [gpg signature key] --volsize=250 --include=/home/[user]/Documents --include=/home/[user]/Projects --include=/home/[user]/Videos --include=/home/[user]/Pictures --exclude=/** / s3+http://[bucketname] 

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export PASSPHRASE=
